--- !ruby/object:Jumpstart::Configuration
application_name: Auto Answer
business_name: SAS Auto Answer
domain: example.com
support_email: bonjour@auto-answer.com
default_from_email: Jumpstart <support@example.com>
business_address: 2 place Antonin Jutard 69003 Lyon
background_job_processor: async
email_provider: ''
personal_accounts: true
solargraph: false
register_with_account: false
apns: false
fcm: false
collect_billing_address: false
