--- !ruby/object:Jumpstart::Configuration
application_name: Auto Answer
business_name: SAS Auto Answer
business_address: 2 place Antonin Jutard 69003 Lyon
domain: example.com
default_from_email: Jumpstart <support@example.com>
support_email: bonjour@auto-answer.com
background_job_processor: async
email_provider: ''
personal_accounts: true
solargraph: false
register_with_account: false
apns: false
fcm: false
collect_billing_address: true
omniauth_providers:
- google-oauth2
payment_processors:
- stripe
